### ISSUE TITLE
Question about missing features

### ISSUE THREAD

**Issue by Bigjango13** [RandomSoup/sack#3]
So far there are no methods to read/write from a file, no classes, no way to get command line options, no input methods, and no `break` or `continue`.
Are these left out for a reason?

Another question I have is why is networking specifically left out?

**Comment by Luminoso-256** [comment]
fwiw classes aren't a nessecary  feature for  a language. In fact, for something lightweight like sack I think the trait & struct system would be more useful. Also, as a scripting language, it's open to extensions based on the embedding environment. I'd imagine that's why I/O is left out.

**Comment by nobody5050** [comment]
That’s *exactly* why I/O is left out.

**Comment by StealthHydra179** [comment]
are break and continue strictly necessary? their use can be replaced with if statements, variables, and rearranging of code, yes its more cumbersome and looks worse, but is it necessary because it is supposed to be lightweight 🤔

**Comment by megaboi2005** [comment]
> are break and continue strictly necessary? their use can be replaced with if statements, variables, and rearranging of code, yes its more cumbersome and looks worse, but is it necessary because it is supposed to be lightweight 🤔

Break should be a thing, it shouldn't ruin the lightweight aspect of the language so why not. It's supposed to be easy for beginners so why not add functionality that makes it easy. 

Input should be a thing too.

**Comment by nobody5050** [comment]
I feel like input would be something for the standard library but if you want to make a pull request for the rest of that stuff, be my guest.
