### ISSUE TITLE
Enforced Style Guide

### ISSUE THREAD

**Issue by StealthHydra179** [RandomSoup/sack#6]
https://github.com/RandomSoup/sack/blob/9ee412a53d09e1879d5f0a9ce1319b9db5943ab9/readme.md?plain=1#L26

For consistency between sack compilers, a selection of one or the other should probably be made (like a warning).

**Comment by Bigjango13** [comment]
It would be easier for compilers to have a separate option for checking style consistency. It may be tiring for a programmer to get bogged down with minor style errors while trying to concentrate on the program itself.

**Comment by StealthHydra179** [comment]
Wouldn't it be better to have the spec state that style guide is default warning, and with a flag an error?

**Comment by Bigjango13** [comment]
> Wouldn't it be better to have the spec state that style guide is default warning, and with a flag an error?

For consistency between sack compilers yes, but it's probably better to have a flag to enable the style warnings in the first place so writing and testing code can separate from cleaning it up.

**Comment by StealthHydra179** [comment]
I would make it a flag to disable warnings instead, as style warnings are something that should be followed unless explicitly ignored.

**Comment by nobody5050** [comment]
Default warn is probably best, this is a holdover from when I was first writing it
